pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/juanantoniotora/TFM_IngenieriaDeTelecomunicacion.git'
            }
        }

        stage('Build') {
            steps {
                dir('demo') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('demo') {
                    sh 'mvn test'
                }
            }
        }

        stage('Run') {
            steps {
                dir('demo') {
                    sh 'java -jar target/*.jar &'
                }
            }
        }
    }
}
