pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/tuusuario/tu-repo.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Run') {
            steps {
                sh 'java -jar target/*.jar &'
            }
        }
    }
}
