pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/juanantoniotora/TFM_IngenieriaDeTelecomunicacion.git'
            }
        }

        stage('Build') {
            steps {
                dir('App BackTutorial/demo') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('App BackTutorial/demo') {
                    sh 'mvn test'
                }
            }
        }

        
        stage('Debug') {
            steps {
                sh 'ls -la'
                sh 'ls -la "App BackTutorial/demo"'
            }
        }

        stage('Run') {
            steps {
                dir('App BackTutorial/demo') {
                    sh 'java -jar target/demo-0.0.1-SNAPSHOT.jar'
                }
            }
        }
    }
}
